### ISSUE TITLE
Extra whitespace after INFO log entries but not WARN or ERROR log entries

### ISSUE THREAD

**Issue by mattwarkentin** [johnmyleswhite/log4r#15]
Hi @johnmyleswhite,

I am relatively new to using this package but I quite like it for being able to easily log warnings and error messages. I noticed when logging to console or to file, there is additional whitespace after `INFO` level messages, but not for some other levels. Is this a standard way of representing `INFO` as different? Is this configurable? Am I doing something wrong?

Here is a reprex for what I observed:
``` r
library(log4r)

logger <- logger()

foo <- function() {
  x <- runif(1)
  if (x < 0.5) message(x) else if (x>0.5 & x<0.75) warning("Warning!") else stop("Error!")
}

purrr::walk(
  1:10, 
  ~tryCatch(
    foo(), 
    message = function(c) info(logger, conditionMessage(c)),
    error = function(c) error(logger, conditionMessage(c)), 
    warning = function(c) warn(logger, conditionMessage(c))
    )
  )
#> INFO  [2020-07-03 18:10:19] 0.113604113692418
#> 
#> ERROR [2020-07-03 18:10:19] Error!
#> WARN  [2020-07-03 18:10:19] Warning!
#> WARN  [2020-07-03 18:10:19] Warning!
#> WARN  [2020-07-03 18:10:19] Warning!
#> WARN  [2020-07-03 18:10:19] Warning!
#> INFO  [2020-07-03 18:10:19] 0.0513754677958786
#> 
#> WARN  [2020-07-03 18:10:19] Warning!
#> WARN  [2020-07-03 18:10:19] Warning!
#> INFO  [2020-07-03 18:10:19] 0.376045615877956
```

**Comment by atheriel** [comment]
Yes, this is expected. It matches the behaviour of log4j's default log layout, which pads the level to 5 characters. It's very easy to control, though, by writing your own layout function. See `?layouts` for details.

**Comment by mattwarkentin** [comment]
Sorry, I didn't mean the character padding on the level text, I meant the extra blank line added after `INFO` levels logs.

**Comment by atheriel** [comment]
Ah. That's a different issue: `message()` adds a newline while `warning()` and `stop()` do not. Try
```
message(x, appendLF = FALSE)
```

**Comment by mattwarkentin** [comment]
Ah yes, this does it. Thanks!
